// Code generated by "enumer -type=Type"; DO NOT EDIT

package storage

import (
	"fmt"
)

const _Type_name = "DiskvS3SpacesRedis"

var _Type_index = [...]uint8{0, 5, 7, 13, 18}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}

var _TypeNameToValue_map = map[string]Type{
	_Type_name[0:5]:   0,
	_Type_name[5:7]:   1,
	_Type_name[7:13]:  2,
	_Type_name[13:18]: 3,
}

func TypeString(s string) (Type, error) {
	if val, ok := _TypeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Storage Type values", s)
}
